import React, { memo, useState } from 'react';

interface GenerationPanelProps {
  isGenerating: boolean;
  images: string[];
  onAddToCanvas: (imageUrl: string) => void;
  onDelete: (index: number) => void;
  t: (key: string) => string;
}

const GenerationPanelComponent: React.FC<GenerationPanelProps> = ({
  isGenerating,
  images,
  onAddToCanvas,
  onDelete,
  t,
}) => {
  const [isOpen, setIsOpen] = useState(true);

  return (
    <>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="absolute top-4 z-20 p-2.5 bg-white/90 backdrop-blur-md rounded-full shadow-xl border border-gray-200 hover:bg-gray-100 transition-all duration-300 ease-in-out"
        style={{ right: isOpen ? 'calc(1rem + 20rem + 0.5rem)' : '1rem' }}
        aria-label={
          isOpen
            ? t('closeGenerationPanel') || '關閉生成面板'
            : t('openGenerationPanel') || '開啟生成面板'
        }
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          className={`h-5 w-5 text-gray-700 transition-transform ${isOpen ? '' : 'rotate-180'}`}
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          strokeWidth={2.5}
        >
          <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
        </svg>
      </button>

      <div
        data-testid="generation-panel"
        className={`absolute top-0 right-0 h-full z-20 p-4 bg-white/80 backdrop-blur-sm shadow-lg border-l border-gray-200 w-80 flex flex-col gap-4 transition-transform duration-300 ${isOpen ? 'translate-x-0' : 'translate-x-full'}`}
      >
        <div>
          <h1 className="text-xl font-bold text-gray-800">
            {t('generationHistory') || '生成歷史'}
          </h1>
          <p className="text-sm text-gray-600 mt-1">
            {t('generationHistoryDesc') || '生成的圖片會顯示在這裡。'}
          </p>
        </div>

        <div className="flex-grow overflow-y-auto pr-2 -mr-2 space-y-4">
          {isGenerating && <p>{t('generating') || '生成中...'}</p>}

          {images.length === 0 && !isGenerating && (
            <p>
              {t('generationHistoryEmpty') ||
                '在畫布上選擇元素並點擊「生成」來建立圖片。'}
            </p>
          )}

          {images.map((imgSrc, index) => (
            <div
              key={index}
              className="group relative border rounded-lg p-2 flex flex-col gap-2 bg-gray-100/50 shadow-sm"
            >
              <img
                src={imgSrc}
                alt={`Generated by AI ${index + 1}`}
                className="w-full h-auto object-contain rounded-md"
              />

              <button
                onClick={() => onAddToCanvas(imgSrc)}
                className="w-full mt-1 px-3 py-1.5 text-sm bg-green-600 text-white rounded-md hover:bg-green-700"
              >
                {t('addToCanvas') || '新增至畫布'}
              </button>

              <button
                onClick={() => onDelete(index)}
                className="absolute top-1 right-1 bg-black/50 text-white rounded-full w-6 h-6 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity hover:bg-red-600"
                aria-label={t('deleteImage') || '刪除圖片'}
              >
                &times;
              </button>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export const GenerationPanel = memo(GenerationPanelComponent);
